spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://talktoyou_mysql:3306/talk_to_you
    username: root
    password: talk_to_you
#logging:
#  level: debug
#    com.example.server

server:
  port: 9090

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启控制台打印日志
  global-config:
    db-config:
      id-type: assign_id                                  # 设置全局主键自增规则
      logic-delete-field: deleted                          # 设置全局逻辑删除
  type-aliases-package:  com.example.server.model